config/routes.rb
Rails.application.routes.draw do
  resources :places
  root 'places#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  http_basic_authenticate_with :name => ENV['BASIC_AUTH_USERNAME'], :password => ENV['BASIC_AUTH_PASSWORD'] if Rails.env == "production"
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all.order(date: :desc)
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:date, :weather, :place, :memo, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,shrink-to-fit=no">
    <title>OdekakeApp</title>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c:500|Roboto&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body ontouchstart="">
    <%= yield %>
    <footer>
      © 2019 <a href="https://github.com/becolomochi">becolomochi</a>
    </footer>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :weather %>
    <%= form.text_field :weather, :class => 'wide' %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place, :class => 'wide' %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo, :rows=>"5" %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, :class => 'wide' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<main>
<h1>編集する</h1>

<%= render 'form', place: @place %>

<%= link_to '詳細画面', @place %> |
<%= link_to '一覧に戻る', places_path %>
</main>

app/views/places/index.html.erb
<main class="main-index">
<p id="notice"><%= notice %></p>

<h1>お出かけアプリ</h1>

<div class="add-link-box">
<%= link_to '新しく登録する', new_place_path %>
</div>

<% @places.each do |place| %>
<article class="article-box">
<div class="article-header">
  <div class="article-date-box">
    <span class="article-date"><%= place.date %></span>
  </div>
  <div class="article-weather-box">
    <span class="article-weather"><%= place.weather %></span>
  </div>
</div>
<div class="article-main">
  <div class="article-place-box">
    <span class="article-place"><%= place.place %></span>
  </div>
  <div class="article-memo-box">
    <div class="article-memo">
      <%= simple_format(place.memo) %>
    </div>
    <%= image_tag(place.picture_url) if place.picture.present? %>
  </div>
</div>
<div class="article-footer">
  <div class="article-links">
    <div class="article-left-link">
      <span class="article-link"><%= link_to '詳細を見る', place %></span>
      <span class="article-link"><%= link_to '編集する', edit_place_path(place) %></span>
    </div>
    <div class="article-right-link">
      <span class="article-link"><%= link_to '削除', place, method: :delete, data: { confirm: '本当に削除しますか？' }, :class =>'delete-link' %></span>
    </div>
  </div>
</div>
</article>
<% end %>
</main>

app/views/places/new.html.erb
<main>
<h1>新しく登録する</h1>

<%= render 'form', place: @place %>

<%= link_to '一覧に戻る', places_path %>
</main>

app/views/places/show.html.erb
<main>
<p id="notice"><%= notice %></p>

<h1>詳細</h1>

<div class="show-item">
  <h3 class="title">日にち:</h3>
  <%= @place.date %>
</div>

<div class="show-item">
  <h3 class="title">天気:</h3>
  <%= @place.weather %>
</div>

<div class="show-item">
  <h3 class="title">出かけた場所:</h3>
  <%= @place.place %>
</div>

<div class="show-item">
  <h3 class="title">メモ:</h3>
  <%= simple_format(@place.memo) %>
</div>

<div class="show-item">
  <h3 class="title">画像:</h3>
  <%= image_tag(@place.picture_url) if @place.picture.present? %>
</div>

<%= link_to '編集する', edit_place_path(@place) %> |
<%= link_to '一覧に戻る', places_path %>
</main>